version: '3.9'

services:

  parser:
    build:
      context: .
      dockerfile: Dockerfile.parser
    restart: on-failure
    depends_on:
      - mongo_prod
      - mongo_dev
    networks:
      - recipes
    profiles:
      - prod
      - dev
    volumes:
      - ./.artifacts/recipes_data/:/app/recipes_data

  mongo_prod:
    image: mongo:4.4
    command: "mongod --dbpath /data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - recipes
    profiles:
      - prod
    volumes:
      - ./mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-mongo-init.js:ro
      - ./.artifacts/mongo/:/data/db

  mongo_dev:
    image: mongo:4.4
    command: "mongod --dbpath /data/db"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    networks:
      - recipes
    profiles:
      - dev
    volumes:
      - ./mongo/init/mongo-init.js:/docker-entrypoint-initdb.d/mongo-mongo-init.js:ro
      - ./.artifacts/mongo/:/data/db
    ports:
      - 27017:27017

networks:
  recipes:
    name: recipes