FROM python:3.8

WORKDIR /app

COPY ./parser/ ./
COPY ./requirements.txt ./requirements.txt
COPY .env ./.env

RUN pip install --upgrade pip && \
    pip install -r requirements.txt

CMD ["python3", "parser.py"]